### backward

POST https://awaleed-es.herokuapp.com/think HTTP/1.1
content-type: application/json

{"q":"no flight,feather","v":true,"m":"backward"}

### forward

POST https://awaleed-es.herokuapp.com/think HTTP/1.1
content-type: application/json

{"q":"no flight, feather","v":false,"m":"forward"}