### backward

POST http://127.0.0.1:5000/think HTTP/1.1
content-type: application/json

{"q":"medium","v":false,"m":"backward"}

### forward

POST http://127.0.0.1:5000/think HTTP/1.1
content-type: application/json

{"q":"no flight, feather","v":false,"m":"forward"}

###  clause

GET http://127.0.0.1:5000/clause HTTP/1.1
content-type: application/json

### PUT clause

PUT http://127.0.0.1:5000/clause HTTP/1.1
content-type: application/json

### PUT knowledge

PUT http://127.0.0.1:5000/knowledge HTTP/1.1
content-type: application/json
